### ISSUE TITLE
Cannot resolve symbol 'CefJavaManager' or 'CefClientManager'

### ISSUE THREAD

**Issue by rqce** [denis-akazuki/samp-mobile-cef#1]
![image](https://github.com/user-attachments/assets/7d4f7fdf-5aa2-4ca5-b303-e632cce7a212)
як фiксити?)

**Comment by denis-akazuki** [comment]
В документації не вистачає інформації про необхідні імпорти для використання цих класів, додам пізніше.

Потрібно додати наступні імпорти до коду (десь в початок, де всі імпорти знаходяться):
```java
import com.akazuki.sampmobilecef.CefClientManager;
import com.akazuki.sampmobilecef.CefJavaManager;
```

**Comment by rqce** [comment]
вони iмпортуються з libs/?

**Comment by denis-akazuki** [comment]
Так, вони імпортуються з бібліотеки. Попередньо цю бібліотеку потрібно під'єднати в `app/build.gradle`. Більш детально це описано в документації - [тут](https://github.com/denis-akazuki/samp-mobile-cef/blob/master/docs/uk/client.md#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%96-%D0%BD%D0%B0%D0%BB%D0%B0%D1%88%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%BA%D0%BB%D1%96%D1%94%D0%BD%D1%82%D1%81%D1%8C%D0%BA%D0%BE%D1%97-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B8-java).

**P.S.** Якщо є труднощі з під'єднанням бібліотеки, то прикріпіть код з вашого `app/build.gradle` та скріншот з папки `app/libs/`
