### ISSUE TITLE
use of undeclared identifier 'cef'

### ISSUE THREAD

**Issue by rqce** [denis-akazuki/samp-mobile-cef#2]
Помилка в клiентi.

![image](https://github.com/user-attachments/assets/88df7be6-1b0c-4686-9a3c-11116a027f2a)

**Comment by denis-akazuki** [comment]
Відсутній імпорт заголовкового файлу в вашому `netgame.cpp`:
```cpp
#include "../vendor/cef/SAMPMobileCef.h" // на початок файлу netgame.cpp
```
