### ISSUE TITLE
Possibility to create multiple WebView instances

### ISSUE THREAD

**Issue by Rayavitor** [denis-akazuki/samp-mobile-cef#4]
In the next version, could you add the option to create more than one browser? For example: CefInitBrowser(playerid, url[], browserId) and CefDestroyBrowser(playerid, browserId), etc.

**Comment by denis-akazuki** [comment]
Hi. I have a suspicion that not every smartphone can handle the load of multiple WebView instances. You can use a single instance, and in your code load the required interface using JavaScript.

**Comment by Rayavitor** [comment]
Thank you for your response.
