### ISSUE TITLE
Build Ready file .so

### ISSUE THREAD

**Issue by Eeykal46** [denis-akazuki/samp-mobile-cef#6]
this kind of tutorial is hard

**Comment by Eeykal46** [comment]
make to build, The file is ready armeabi-v7a, build ready, directly put the .so file into the lib/armeabi-v7a file, it's hard for this kind of thing

**Comment by denis-akazuki** [comment]
Hello. The project is delivered as a module, because each mobile client has its own unique implementation. The instructions are very simple, and you always have the option to create a new issue with any difficulties you may have.

**Comment by Eeykal46** [comment]
Please video tutorial build
